using System;
using System.Linq;
using System.CodeDom.Compiler;
using System.Collections.Generic;

namespace RedEye.Core.ScriptEngine {
    public class CSharpHandler : IScriptHandler {
        string codeTemplate = @"
            using System;
            using RedEye.Core;

            public class _ScriptAutoGenerated {{
                public static void _ScriptEntryPoint({0}){{
                    {1}
                }}
            }}
        ";

        public void EvaluateCode(string code, IDictionary<string, object> nameSpace, IDictionary<string, object> parameters = null){
            if(parameters is null || !parameters.ContainsKey("disableInlineScriptMode")){
                List<string> args = new();
                foreach(var kvp in nameSpace){
                    args.Add($"{kvp.Value.GetType().FullName} {kvp.Key}");
                }

                var argList = string.Join(", ", args);
                code = string.Format(codeTemplate, argList, code);
            }
            

            var result = CSharpHelper.CompileCode(code);

            if(!result.Success){
                List<string> errors = new();
                foreach(CompilerError err in result.Errors){
                    errors.Add($"C# compile error at {err.Line}: {err.ErrorText}");
                }

                throw new ScriptEngineException(string.Join("; ", errors));
            }

            try{
                var type = (parameters is not null && parameters.ContainsKey("entryPointType")) ? (string)parameters["entryPointType"] : "_ScriptAutoGenerated";
                var method = (parameters is not null && parameters.ContainsKey("entryPointMethod")) ? (string)parameters["entryPointMethod"] : "_ScriptEntryPoint";

                result.Assembly.GetType(type).GetMethod(method).Invoke(null, nameSpace.Values.ToArray());
            }catch(Exception ex){
                throw new ScriptEngineException($"C# runtime error: {ex.GetType().FullName}: {ex.Message} | inner exception: {(ex.InnerException is not null ? ex.InnerException.GetType().FullName : string.Empty)} {(ex.InnerException is not null ? ex.InnerException.Message : string.Empty)}");
            }
        }
    }
}